const loginView=document.getElementById('loginView');const adminView=document.getElementById('adminView');const loginForm=document.getElementById('loginForm');const configForm=document.getElementById('configForm');const deviceForm=document.getElementById('deviceForm');const loginStatus=document.getElementById('loginStatus');const configStatus=document.getElementById('configStatus');const enrollmentResult=document.getElementById('enrollmentResult');const deviceList=document.getElementById('deviceList');const storageNotice=document.getElementById('storageNotice');const versionLabel=document.getElementById('versionLabel');
loginForm.addEventListener('submit',async e=>{e.preventDefault();setStatus(loginStatus,'Ingresando...');const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.getElementById('username').value,password:document.getElementById('password').value})});const d=await safeJson(r);if(!r.ok){setStatus(loginStatus,d?.error||'No fue posible ingresar.','error');return}document.getElementById('password').value='';await loadConfig();await loadDevices();});
document.getElementById('logoutButton').addEventListener('click',async()=>{await fetch('/api/admin/login',{method:'DELETE'});showLogin()});
configForm.addEventListener('submit',async e=>{e.preventDefault();setStatus(configStatus,'Guardando...');const r=await fetch('/api/admin/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({improvePrompt:document.getElementById('improvePrompt').value,assistantPrompt:document.getElementById('assistantPrompt').value,knowledgeBase:document.getElementById('knowledgeBase').value})});const d=await safeJson(r);if(r.status===401){showLogin();return}if(!r.ok){setStatus(configStatus,d?.error||'No fue posible guardar.','error');return}applyConfig(d.config);setStatus(configStatus,'Configuración guardada correctamente.','success')});
deviceForm.addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('newDeviceName').value.trim();if(!name)return;setStatus(enrollmentResult,'Generando código...');const r=await fetch('/api/admin/devices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceName:name})});const d=await safeJson(r);if(r.status===401){showLogin();return}if(!r.ok){setStatus(enrollmentResult,d?.error||'No fue posible generar el código.','error');return}const expiry=new Intl.DateTimeFormat('es-CO',{timeStyle:'short'}).format(new Date(d.enrollment.expiresAt));setStatus(enrollmentResult,`Código: ${d.enrollment.code} · válido hasta ${expiry}`,'success');document.getElementById('newDeviceName').value='';});
async function loadConfig(){const r=await fetch('/api/admin/config',{cache:'no-store'});const d=await safeJson(r);if(r.status===401){showLogin();return}if(!r.ok){setStatus(loginStatus,d?.error||'No fue posible cargar la configuración.','error');return}applyConfig(d.config);loginView.classList.add('hidden');adminView.classList.remove('hidden')}
async function loadDevices(){const r=await fetch('/api/admin/devices',{cache:'no-store'});const d=await safeJson(r);if(r.status===401){showLogin();return}if(!r.ok){deviceList.textContent=d?.error||'No fue posible cargar equipos.';return}renderDevices(d.devices||[])}
function renderDevices(devices){deviceList.innerHTML='';if(!devices.length){deviceList.textContent='No hay equipos activados todavía.';return}devices.forEach(device=>{const row=document.createElement('div');row.className='device-row';const info=document.createElement('div');const seen=device.lastSeenAt?new Intl.DateTimeFormat('es-CO',{dateStyle:'short',timeStyle:'short'}).format(new Date(device.lastSeenAt)):'Sin uso';info.innerHTML=`<strong>${escapeHtml(device.deviceName||'Equipo')}</strong><small>${escapeHtml(device.status)} · Último uso: ${escapeHtml(seen)}</small>`;row.appendChild(info);if(device.status==='active'){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Revocar';button.onclick=async()=>{const r=await fetch('/api/admin/devices',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({deviceId:device.deviceId})});if(r.ok)await loadDevices();};row.appendChild(button)}deviceList.appendChild(row)})}
function applyConfig(config){document.getElementById('improvePrompt').value=config.improvePrompt||'';document.getElementById('assistantPrompt').value=config.assistantPrompt||'';document.getElementById('knowledgeBase').value=config.knowledgeBase||'';versionLabel.textContent=`Versión ${config.version||1}`;storageNotice.classList.toggle('show',!config.storageReady);storageNotice.textContent=config.storageReady?'':'Falta conectar Vercel Blob privado. La activación de equipos también requiere este almacenamiento.'}
function showLogin(){adminView.classList.add('hidden');loginView.classList.remove('hidden');setStatus(loginStatus,'')}function setStatus(el,text,type=''){el.textContent=text;el.className=`status ${type}`.trim()}async function safeJson(r){try{return await r.json()}catch{return null}}function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}loadConfig().then(()=>{if(!adminView.classList.contains('hidden'))loadDevices()});
