const loginView=document.getElementById('loginView');const adminView=document.getElementById('adminView');const loginForm=document.getElementById('loginForm');const configForm=document.getElementById('configForm');const loginStatus=document.getElementById('loginStatus');const configStatus=document.getElementById('configStatus');const storageNotice=document.getElementById('storageNotice');const versionLabel=document.getElementById('versionLabel');

loginForm.addEventListener('submit',async(e)=>{e.preventDefault();setStatus(loginStatus,'Ingresando...');const response=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.getElementById('username').value,password:document.getElementById('password').value})});const data=await safeJson(response);if(!response.ok){setStatus(loginStatus,data?.error||'No fue posible ingresar.','error');return}document.getElementById('password').value='';await loadConfig()});

document.getElementById('logoutButton').addEventListener('click',async()=>{await fetch('/api/admin/login',{method:'DELETE'});showLogin()});

configForm.addEventListener('submit',async(e)=>{e.preventDefault();setStatus(configStatus,'Guardando...');const response=await fetch('/api/admin/config',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({improvePrompt:document.getElementById('improvePrompt').value,assistantPrompt:document.getElementById('assistantPrompt').value,knowledgeBase:document.getElementById('knowledgeBase').value})});const data=await safeJson(response);if(response.status===401){showLogin();return}if(!response.ok){setStatus(configStatus,data?.error||'No fue posible guardar.','error');return}applyConfig(data.config);setStatus(configStatus,'Configuración guardada correctamente.','success')});

async function loadConfig(){const response=await fetch('/api/admin/config',{cache:'no-store'});const data=await safeJson(response);if(response.status===401){showLogin();return}if(!response.ok){setStatus(loginStatus,data?.error||'No fue posible cargar la configuración.','error');return}applyConfig(data.config);loginView.classList.add('hidden');adminView.classList.remove('hidden')}
function applyConfig(config){document.getElementById('improvePrompt').value=config.improvePrompt||'';document.getElementById('assistantPrompt').value=config.assistantPrompt||'';document.getElementById('knowledgeBase').value=config.knowledgeBase||'';versionLabel.textContent=`Versión ${config.version||1}`;storageNotice.classList.toggle('show',!config.storageReady);storageNotice.textContent=config.storageReady?'':'Falta conectar Vercel Blob privado. Puede revisar el contenido, pero no guardarlo todavía.'}
function showLogin(){adminView.classList.add('hidden');loginView.classList.remove('hidden');setStatus(loginStatus,'')}
function setStatus(element,text,type=''){element.textContent=text;element.className=`status ${type}`.trim()}
async function safeJson(response){try{return await response.json()}catch{return null}}
loadConfig();
